apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: testuserrb
subjects:
- kind: ServiceAccount
  name: testuser
  namespace: default
roleRef:
  kind: Role
  name: testuser
  apiGroup: rbac.authorization.k8s.io
